### ISSUE TITLE
Feature request: Consistency in naming variables

### ISSUE THREAD

**Issue by cyplessen** [MathiasHarrer/metapsyTools#1]
As we talked about, it would be great if we could have consistent variable names and change them to snake_case  and rename a few others:

- condition instead of cond_spec 
- condition_description instead of cond_legacy 
- instrument instead of outc_measure
- _arm suffix instead of _trt

**Comment by MathiasHarrer** [comment]
Perfect! So if i:

1. Change all required variable names to `snake_case` (+ change defaults and toy dataset vars accordingly)
2. Change the 4 varnames as described by you above 

We arrive at a consistent coding scheme that we can stick with for the foreseeable future? 
I would then change this in the next release (which I plan to push to the `metapsy-project` user already) + update the docs

@metapsy-project @clara-miguel
